#!/bin/bash

set -e
set -x

# install node 0.12.5
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.25.4/install.sh | bash
. ~/.nvm/nvm.sh
nvm install v0.12.5
nvm use 0.12.5

# install local dependencies
rm -rf node_modules
npm install

# lint source
./node_modules/.bin/eslint gulpfile.js karma.*conf.js apps scripts/gen* scripts/lib scripts/tasks scripts/test scripts/tools scripts/slushfile.js -f checkstyle -o checkstyle-result.xml || true

# run tests
Xvfb :1 -screen 5 1024x768x8 &
export DISPLAY=:1.5
./node_modules/.bin/karma start karma.ci.conf.js
