#!/bin/bash

# set -e
# set -x
#
# # install node 0.12.5
# curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.25.4/install.sh | bash
# . ~/.nvm/nvm.sh
# nvm install v0.12.5
# nvm use 0.12.5
#
# # install local dependencies
# rm -rf node_modules
# npm install
#
# # build apps
# ./node_modules/.bin/gulp build
